version: "3.8"
services:
  backend:
    platform: linux/amd64
    build:
      context: backend
    ports:
      - "3000:3000"
  frontend-prod:
    platform: linux/amd64
    build:
      context: frontend
      target: production
    ports:
      - "80:3000"
    depends_on:
      - backend

  frontend-dev:
    platform: linux/amd64
    build:
      context: frontend
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
