services:
  backend:
    platform: linux/amd64
    build:
      context: backend
    depends_on:
      - db
    env_file: .env
    ports:
      - "3000:80"
    networks:
      - synap-network
  db:
    platform: linux/amd64
    image: postgres:17
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data # Volume to persist data
    ports:
      - "5432:5432" # Expose PostgreSQL port
    networks:
      - synap-network

  frontend-prod:
    platform: linux/amd64
    build:
      context: frontend
      target: prod
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    ports:
      - "80:80"
    depends_on:
      - backend
      - db
    networks:
      - synap-network
    env_file: .env

volumes:
  postgres_data:

networks:
  synap-network:
    driver: bridge
