from .course_repository import CourseRepository
from .learning_material_repository import LearningMaterialRepository
from .note_repository import NoteRepository
from .recommendation_repository import RecommendationRepository
from .summarization_repository import SummarizationRepository
from .uploaded_files_repository import UploadedFileRepository
from .user_repository import UserRepository
