from .course_service import CourseService
from .learning_material_service import LearningMaterialService
from .note_service import NoteService
from .recommendation_service import RecommendationService
from .uploaded_files_service import UploadedFileService
from .user_service import UserService