from models.user import User
from models.course import Course
from models.note import Note
from models.file import UploadedFile
from models.summarization import Summarization
from models.tag import Tag
from models.file_tag import FileTag
from models.learning_material import LearningMaterial
from models.learning_material_tag import LearningMaterialTag
from models.recommendation import Recommendation
