"""openai_id column added for uploaded_files

Revision ID: 13da4c5ccce5
Revises: 0376df85f115
Create Date: 2025-05-17 15:16:56.974429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13da4c5ccce5'
down_revision: Union[str, None] = '0376df85f115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_files', sa.Column('openai_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_files', 'openai_id')
    # ### end Alembic commands ###
