"""learning_material_tags table

Revision ID: 9b784bc1bdb5
Revises: 97b1f394c96d
Create Date: 2025-04-16 17:37:47.031427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b784bc1bdb5'
down_revision: Union[str, None] = '97b1f394c96d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_material_tags',
    sa.Column('learning_material_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['learning_material_id'], ['learning_materials.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('learning_material_id', 'tag_id', name='learning_material_tag_pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_material_tags')
    # ### end Alembic commands ###
