"""Default UUID keys

Revision ID: ca9ac93b141f
Revises: abc22c9bfac3
Create Date: 2025-05-06 12:24:21.012515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca9ac93b141f'
down_revision: Union[str, None] = 'abc22c9bfac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    
    op.alter_column(
        'uploaded_files',
        'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()') 
    )

    
    op.alter_column(
        'recommendation_interactions',
        'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()') 
    )
    
    
    op.alter_column(
        'summarizations',
        'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()') 
    )

    
    op.alter_column(
        'learning_materials',
        'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()') 
    )

    op.alter_column(
        'courses',
        'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()') 
    )

    
    op.alter_column(
        'courses',
        'updated_at',
        existing_type=sa.DateTime(timezone=True),
        server_default=sa.text('now()')
    )

def downgrade() -> None:
    """Downgrade schema."""
    # Ne pisuvam downgrade :D
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
