name: Build and Publish Images

on:
  push:
    branches: ["master"]
  workflow_dispatch:

env:
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY_FRONTEND: synap-frontend
  ECR_REPOSITORY_BACKEND: synap-backend
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest

    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4

        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Frontend Image
        run: |
          docker build \
            --platform linux/amd64 \
            -t $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:latest \
            -f frontend/Dockerfile \
            ./frontend 
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND --all-tags
        working-directory: .

      - name: Build and Push Backend Image
        run: |
          docker build \
            --platform linux/amd64 \
            -t $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:latest \
            -f backend/Dockerfile \
            ./backend 
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND --all-tags
        working-directory: .
